# Generated by Django 4.1.7 on 2023-03-12 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("category", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name": "Category", "verbose_name_plural": "categories"},
        ),
        migrations.RenameField(
            model_name="category", old_name="slug", new_name="category_slug",
        ),
        migrations.AddField(
            model_name="category",
            name="category_slug_uuid",
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="category",
            name="description",
            field=models.TextField(blank=True),
        ),
    ]
