# Generated by Django 4.1.7 on 2023-03-12 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("category", "0002_alter_category_options_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="category", old_name="category_slug", new_name="slug",
        ),
        migrations.RenameField(
            model_name="category", old_name="category_slug_uuid", new_name="slug_uuid",
        ),
    ]
