# Generated by Django 4.1.7 on 2023-03-12 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("category", "0003_rename_category_slug_category_slug_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="category", old_name="slug", new_name="category_slug",
        ),
        migrations.RenameField(
            model_name="category", old_name="slug_uuid", new_name="category_slug_uuid",
        ),
    ]
